### PR TITLE
Bugfix/sycl buffers attempt two

### PR DESCRIPTION
**Pull request by will-saunders-ukaea**
# Description

Refactors the original 1D implementation with a focus on compliance rather than performance. Solves issue #190.

Tests now pass on GPU devices (hipsycl+nvcxx backend). Tests on CPU backends pass as before.

### CODE REVIEW

**Comment by jwscook** [comment]
Should this also have fixed the mesh problems we had with the unit tests? I'm getting

```
[ RUN      ] MeshTest.set_initial_field
free(): invalid next size (fast)
```

when running the oneapi unittests.

**Comment by will-saunders-ukaea** [comment]
@jwscook Do you know which oneapi version this was with? Trying to reproduce.

**Comment by jwscook** [comment]
@jwscook do this!

**Comment by jwscook** [comment]
@JamesEdgeley could you review and merge if passes please :)

**Pull request merged**
