### PR TITLE
Remove unnecessary lines of CMake

### LINKED ISSUE #136: Redundant lines of CMake
Lines 142-164 of the top-level CMakeLists.txt (quoted below) are now redundant and should have been removed in #118.

```cmake
# Include src folder for header files
target_include_directories(
  ${LIBRARY_NAME} PUBLIC $<INSTALL_INTERFACE:include>
                         $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>)
if(MKL_FOUND)
  target_include_directories(
    ${LIBRARY_NAME}
    PUBLIC $<TARGET_PROPERTY:MKL::MKL,INTERFACE_INCLUDE_DIRECTORIES>)
  target_include_directories(
    ${PROJECT_NAME}
    PUBLIC $<TARGET_PROPERTY:MKL::MKL,INTERFACE_INCLUDE_DIRECTORIES>)
endif()

# Add libraries
target_link_libraries(${LIBRARY_NAME} PUBLIC ${NEKTAR++_LIBRARIES}
                                             ${NEKTAR++_TP_LIBRARIES})
if(MKL_FOUND)
  target_link_libraries(${LIBRARY_NAME} PUBLIC ${CUSTOM_MKL_LINK})
endif()
if(FFTW_FOUND)
  target_link_libraries(${LIBRARY_NAME} PUBLIC PkgConfig::FFTW)
endif()
```

### PR DESCRIPTION
**Pull request by cmacmackin**
# Description

Remove redundant lines in the top-level CMakeLists.txt which should have been removed in #118, but were missed somehow. Also reverts a few things in FindFFT.cmake which were introduced for debugging purposes and not removed before merging #132.

Fixes #136 

## Type of change

- [x] Bug fix (non-breaking change)

# Testing

As this was just a small fix to the build-system, no new test were needed. It was confirmed that all passing tests in the test suite continued to pass. However, `SimpleSOLTest.2D` has segfaulted on my computer prior to making this change (see #137) and continues to do so.

**Test Configuration**:

- OS: Linux Mint 21 (Ubuntu 22.04)
- SYCL implementation: hipSYCL, DPC++
- MPI details: MPICH (for hipSYCL), Intel MPI (for DPC++)
- Hardware: CPU (Intel Icelake)

# Checklist:

- [ ] New and existing unit tests pass locally with my changes
- [x] I have run `cmake-format` against my changes to `CMakeLists.txt`
- [x] I have made corresponding changes to the documentation
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by jwscook** [comment]
Looking at this now

**Comment by jwscook** [comment]
The build works, but now I'm getting segfaults from both builds in the `SimpleSOLTest.2D` fixture (all other fixtures pass, all unitTests pass). I'll just spin up gdb.

**Comment by cmacmackin** [comment]
I was getting that even before this PR. See #137. It has happened _at least_ since #132 was merged.

**Comment by jwscook** [comment]
Infact I might have been using old binaries still in builds. I've clobbered the builds directory but now the symlinks aren't being replenished by `spack install`.

**Comment by jwscook** [comment]
> I was getting that even before this PR. See #137. It has happened _at least_ since #132 was merged.

In that case let's plough on.

**Review by jwscook — APPROVED** [review]

**Comment by cmacmackin** [comment]
> Infact I might have been using old binaries still in builds. I've clobbered the builds directory but now the symlinks aren't being replenished by spack install.

If you deactivate and reactivate the environment that should fix it. It's meant to happen in real time but that could end up breaking sometimes.

**Pull request merged**
