### PR TITLE
Update nektar in NESO to support implicit HW

### LINKED ISSUE #238: Update NESO to include nektar updates required for implicit 2DHW
The required NESO-Spack changes have been made, so this amounts to
- Move nektar submodule pointer
- Set nektar version to @master in spack.yaml
- Cherry pick commits from [tmp/hw-impurities-transport](https://github.com/ExCALIBUR-NEPTUNE/NESO/tree/tmp/hw-impurities-transport) to update the nektar API calls in NESO solvers.

### PR DESCRIPTION
**Pull request by oparry-ukaea**
# Description

Update nektar version to support implicit solve for LAPD / HW.

Fixes #238 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Testing

No new tests

**Test Configuration**:

OS: Ubuntu 22.04
Compiler: GCC 11.3.0 / OneAPI v2022.1.0
SYCL implementation: Hipsycl v0.9.2 / DPC++ v2022.1.0
MPI details: MPICH v4.0.2
Hardware: CPU (Intel Alder Lake)

# Checklist:

- [ ] New and existing unit tests pass locally with my changes
- [x] I have run `clang-format` against my `*.hpp` and `*.cpp` changes
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by oparry-ukaea** [comment]
Integration tests pass except MultipleMeshes/ParticleAdvection3D.Advection3D/0 which fails with
```
Value of: is_contained || (dist < (tol * 10.0))
  Actual: false
Expected: true
```
Unit tests pass except MultipleMeshes/ParticleGeometryInterface.LocalMapping3D/0, which fails with
```
Value of: err_abs <= tol
  Actual: false
Expected: true
```

**Comment by oparry-ukaea** [comment]
@will-saunders-ukaea thinks that the failure of ParticleGeometryInterface.LocalMapping3D could imply that the mapping functions have changed on the nektar side... need to check with Dave to resolve this.

**Comment by will-saunders-ukaea** [comment]
I'm doing some comparative debugging to see if our numbers have changed or if nektar numbers have changed.

**Comment by will-saunders-ukaea** [comment]
Looks like the mappings are fine. The test does one pass of checking the containing geom Nektar finds is the same or next to the one we find, like the integration test does. This is failing like how the integration test does (probably the same dist issue).

**Comment by will-saunders-ukaea** [comment]
Created Nektar++ issue. https://gitlab.nektar.info/nektar/nektar/-/issues/342

**Review by will-saunders-ukaea — APPROVED** [review]
Tests pass for me with hipsycl.

**Comment by oparry-ukaea** [comment]
Test pass for me with gcc and intel; merging

**Pull request merged**
