### PR TITLE
Nektar SOL solver

### PR DESCRIPTION
**Pull request by oparry-ukaea**
# Description

Adds a simple 1D/2D Nektar scrape-off layer solver.
Standalone for now - no coupling with other NESO components.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Requires documentation updates

# Testing

In `test/integration/solvers/SimpleSOL/test_SimpleSOL.cpp`:
- 1D: Compares the final density, velocity and temperature profiles to an analytic solution after Arter, 2015.
- 2D: Performs the same comparisons as the 1D test along a line from (xmin,0) to (xmax,0) in the 2D domain (which is periodic along the y direction).

To minimise duplication, I've added test fixtures for:
- Nektar solvers in general: `test/integration/solvers/solver_test_utils.h` and
- SimpleSOL: `test/integration/solvers/SimpleSOL/test_SimpleSOL.h`

`NektarSolverTest::make_test_run_dir()` creates a temporary run directory, copying in test-specific resources (config, mesh, ICs) and common resources (analytic data, in this case).

# Checklist

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any new dependencies are automatically built for users via `cmake`
- [x] I have used understandable variable names
- [x] I have run `clang-format` against my `*.hpp` and `*.cpp` changes
- [x] I have run `cmake-format` against my changes to `CMakeLists.txt`
- [x] I have made corresponding changes to the documentation
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by oparry-ukaea** [comment]
This is ready for review.
Still some doc updates and enforcement of code style required, but should be ready to go otherwise.  Building requires this change: ExCALIBUR-NEPTUNE/NESO-Spack#13, so until that's merged you'll need to
```
cd NESO-Spack; git fetch && git checkout feature/nektar-compflow-solver-lib; cd -
```
There are now integration tests for the solver in 1D and 2D, which run in ~6 s and ~3 mins respectively on my laptop.  I put a fair bit of effort into reducing those runtimes as far as possible, while still testing something meaningful; if others feel 3 mins is too long, we might want to consider separating solver tests from the rest of the integration tests.

**Comment by jwscook** [comment]
I get this to build on 20.04 with `neso%gcc@11.2.0 ^openblas ^hipsycl` using the `NESO-Spack` branch `feature/gmock-for-neso` that ensures gmock is built (it mysteriously isn't built for me by default).

 - The `unitTests` all pass
 - All the `integrationTests` pass serially and in parallel except Sol1D and Sol2D which segfault if run serially, but pass with 2 or more MPI ranks (only tests 2, 3 and 4).

**Comment by jwscook** [comment]
@oparry-ukaea reports using Scotch 6.04 fixes the segfaulting issues.

**Comment by jwscook** [comment]
Scotch 6.0.4 does not fix the segfaults for me.

**Comment by will-saunders-ukaea** [comment]
Hipsycl+mpich and Oneapi+IntelMPI with Scotch@6.0.4 are both passing unit and integration tests for me in serial and parallel.

**Comment by jwscook** [comment]
Now for no good reason it's not segfaulting with mpich@4.0.2, scotch@6.0.4, hipsycl@0.9.2. Ready merge after a short docs entry intended more for developers than users.

**Comment by oparry-ukaea** [comment]
Ready to merge.

**Review by jwscook — APPROVED** [review]

**Pull request merged**
