### PR TITLE
Refactor cmake to use modern conventions

### LINKED ISSUE #111: Modernise CMake configurations
Currently the CMake configuration relies on manually setting things like include directories and compiler flags based on dependencies. The automatic system for getting this information from linked targets isn't always used. There is also some rather messy logic around searching for different implementations of things like SYCL and FFTW which would be better placed in a `Find<PACKAGE_NAME>` file. This would also allow the creation and exporting of targets for packages which don't provide them themselves. Finally, the installation process should be improved to ensure that everything gets installed and NESO targets are exported for other people to build with.

### LINKED ISSUE #114: CMake install fails on a fresh clone
Executables are no longer placed in ./bin, but the top-level CMakeLists tries to copy the contents of that directory when installing.

### PR DESCRIPTION
**Pull request by cmacmackin**
# Description

This commit represents a fairly comprehensive reworking of the CMake build.

- Removes duplicate find_package calls for MPI (and others)
- Removed commented-out configurations that are not needed
- Places logic for finding and loading SYCL and FFT implementations into separate files, which provide convenient targets to link against
- Create wrapper for loading Nektar++ to provide nicer target to link against
- Avoid using imported variables for setting include directories, compiler flags, etc. and use targets instead
- Explicitly list source files to avoid potential bugs with stale builds (see [CMake documentation](https://cmake.org/cmake/help/latest/command/file.html#glob))
- Ensure build products correctly installed (including exporting CMake configurations)
- Ensured build-type dependent compiler flags were actually used
- Generally tried to simplify the logic, at least in the main CMakeLists files

Fixes #114, fixes #111

## Type of change

Please delete options that are not relevant.

- [x] Build system

# Testing

Ensured that all files compile/link and that unit/integration tests still pass. Checked result of installing and confirmed all expected files are present.

**Test Configuration**:

* OS: Linux Mint 21 (Ubuntu 22.04)
* SYCL implementation: hipSYCL, DPC++
* MPI details: MPICH (for hipSYCL), Intel MPI (for DPC++)
* Hardware: CPU (Intel Icelake)

# Checklist:

- [x] New and existing unit tests pass locally with my changes
- [x] Any new dependencies are automatically built for users via `cmake`
- [x] I have used understandable variable names
- [x] I have run `clang-format` against my `*.hpp` and `*.cpp` changes
- [x] I have run `cmake-format` against my changes to `CMakeLists.txt`
- [x] I have run `black` against changes to `*.py`
- [x] I have made corresponding changes to the documentation
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by cmacmackin** [comment]
Note that I discovered some fragility in the build. Incorrect ordering of some MKL libraries in the link command can result in segfaults at execution, despite the build completing successfully. This is described in more detail in the message of commit [72a8a16](https://github.com/ExCALIBUR-NEPTUNE/NESO/pull/118/commits/72a8a164ad4c1270ef1fcf5cd5ffe44314a9defe). While that problem has been resolved, it revealed some underlying issues which might cause errors later. It is probably worth documenting them somewhere more visible than a commit message.

**Comment by jwscook** [comment]
@oparry-ukaea could you take a look at this one please if you have any time? I've having unrelated build issues on 22.10

**Comment by jwscook** [comment]
I've been able to build this on 22.10 with `neso%gcc@10.4.0 ^openblas ^hipsycl`.

Working on confirming the intel build now.

**Comment by jwscook** [comment]
The recipe is:
 - `spack env deactivate`
 - `spack install intel-oneapi-compilers`
 - `spack compiler find`
 - `spack env activate -p -d .`
 - `spack install`

**Comment by jwscook** [comment]
```
$./test/unitTests -gtest_filter=GeometryTransport2D*
Abort(2139535) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(178)........: 
MPID_Init(1532)..............: 
MPIDI_OFI_mpi_init_hook(1512): 
open_fabric(2566)............: 
find_provider(2684)..........: OFI fi_getinfo() failed (ofi_init.c:2684:find_provider:No data available)
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=2139535
:
system msg for write_line failure : Bad file descriptor
Abort(2139535) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(178)........: 
MPID_Init(1532)..............: 
MPIDI_OFI_mpi_init_hook(1512): 
open_fabric(2566)............: 
find_provider(2684)..........: OFI fi_getinfo() failed (ofi_init.c:2684:find_provider:No data available)
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=2139535
:
system msg for write_line failure : Bad file descriptor
Segmentation fault (core dumped)
```

Last arose when dpcpp was not used as the compiler name for neso.

**Comment by cmacmackin** [comment]
The first of these looks like an MPI error. Wasn't that an issue of which MPI version we were using and what environment variables were set?

The second of these is the error I was encountering and [described in a commit message](https://github.com/ExCALIBUR-NEPTUNE/NESO/pull/118/commits/72a8a164ad4c1270ef1fcf5cd5ffe44314a9defe). Interesting to see it reoccurring. Could you post the link command used for that executable from the build log?

**Comment by jwscook** [comment]
```
[NESO] ┌─29-Nov 15:23:54 cookj ~/code/NESO/spack-build-icobig5 [cmacmackin-refactor-cmake*] 
└─$ldd CombinedSolver.x  | grep libmkl_intel
	libmkl_intel_lp64.so.2 => /home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-mkl-2022.1.0-tjw3qgfmbzknpojxfgvq3rklksgtuqkc/mkl/2022.1.0/lib/intel64/libmkl_intel_lp64.so.2 (0x00007fe91e74b000)
                                                                                                                                                                                        [ 0s023 | Nov 29 03:24pm ]
[NESO] ┌─29-Nov 15:24:15 cookj ~/code/NESO/spack-build-icobig5 [cmacmackin-refactor-cmake*] 
└─$ldd test/unitTests  | grep libmkl_intel
	libmkl_intel_ilp64.so.2 => /home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-mkl-2022.1.0-tjw3qgfmbzknpojxfgvq3rklksgtuqkc/mkl/2022.1.0/lib/intel64/libmkl_intel_ilp64.so.2 (0x00007f936158e000)
	libmkl_intel_lp64.so.2 => /home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-mkl-2022.1.0-tjw3qgfmbzknpojxfgvq3rklksgtuqkc/mkl/2022.1.0/lib/intel64/libmkl_intel_lp64.so.2 (0x00007f9356d4b000)
```

**Comment by cmacmackin** [comment]
Possibly when Nektar++ was being built with DPCPP, MKL knew to link against the 64-bit interface.

**Comment by cmacmackin** [comment]
@jwscook Interesting, but I really need to see what link command was used. I think it should be available in `spack-build-02-build-out.txt`.

**Comment by jwscook** [comment]
`ADRSolver-rg` uses `libmkl_intel_lp64.so.2` which is 32-bit indexing.

**Comment by jwscook** [comment]
> @jwscook Interesting, but I really need to see what link command was used. I think it should be available in `spack-build-02-build-out.txt`.

```
[100%] Linking CXX executable NESO
/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/cmake-3.23.1-asjk2hjev3p4h4eoruf3pwfrdymoeutq/bin/cmake -E cmake_link_script CMakeFiles/NESO.dir/link.txt --verbose=1
/home/cookj/code/spack/lib/spack/env/oneapi/icpx  --dpcpp -fsycl  -O2 -g -DNDEBUG  --dpcpp -fsycl  CMakeFiles/NESO.dir/src/main.cpp.o -o NESO  -Wl,-rpath,/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-mkl-2022.1.0-tjw3qgfmbzknpojxfgvq3rklksgtuqkc/mkl/2022.1.0/lib/intel64:/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-tbb-2021.6.0-kr2hr2l35zruzpu7laubu4uipkkq45xd/tbb/2021.6.0/lib/intel64/gcc4.8:/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/nektar-5.3.0-2e0fb8-5ln7raynmp7smosrm7cpirqobfarlca5/lib64:/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/arpack-ng-3.8.0-4orb5x42icav6oopbxtueejlebvbvouy/lib:/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/zlib-1.2.12-ry4tejpylmzntfbxx6j4wyt6wnpbkipa/lib:/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/tinyxml-2.6.2-gtc5g2ihh7kstp7j6mcjmvoy3b5tx7ym/lib:/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-mpi-2021.6.0-mgejqsr364hldxqtpeyuytll23pf6grl/mpi/2021.6.0/lib:/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/scotch-7.0.1-x2tc54otq7abvfl76ptja6epfe4ysdi6/lib:/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/intel-2021.7.1/boost-1.79.0-tjk6cl63qofhct4aseptpscp5rpi7c6n/lib:/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-mpi-2021.6.0-mgejqsr364hldxqtpeyuytll23pf6grl/mpi/2021.6.0/lib/release::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: libnesolib.a -Wl,-rpath=/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-mkl-2022.1.0-tjw3qgfmbzknpojxfgvq3rklksgtuqkc/mkl/2022.1.0/lib/intel64 /home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-mkl-2022.1.0-tjw3qgfmbzknpojxfgvq3rklksgtuqkc/mkl/2022.1.0/lib/intel64/libmkl_sycl.so /home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-mkl-2022.1.0-tjw3qgfmbzknpojxfgvq3rklksgtuqkc/mkl/2022.1.0/lib/intel64/libmkl_intel_ilp64.so /home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-mkl-2022.1.0-tjw3qgfmbzknpojxfgvq3rklksgtuqkc/mkl/2022.1.0/lib/intel64/libmkl_core.so /home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-mkl-2022.1.0-tjw3qgfmbzknpojxfgvq3rklksgtuqkc/mkl/2022.1.0/lib/intel64/libmkl_tbb_thread.so /home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-tbb-2021.6.0-kr2hr2l35zruzpu7laubu4uipkkq45xd/tbb/2021.6.0/lib/intel64/gcc4.8/libtbb.so.12 -Wl,-rpath,/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-tbb-2021.6.0-kr2hr2l35zruzpu7laubu4uipkkq45xd/tbb/2021.6.0/lib/intel64/gcc4.8 -L/home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/intel-oneapi-tbb-2021.6.0-kr2hr2l35zruzpu7laubu4uipkkq45xd/tbb/2021.6.0/lib/intel64/gcc4.8 -ltbb -lstdc++ -lm -ldl -lpthread -lsycl -lOpenCL /home/cookj/code/spack/opt/spack/linux-ubuntu22.10-skylake/oneapi-2022.2.1/nektar-5.3.0-2e0fb8-5ln7raynmp7smosrm7cpirqobfarlca5/lib64/libSolverUtils-rg.so.5.3.0 /home/cookj/code/spack/opt/spack/linux-u
```

**Comment by cmacmackin** [comment]
As I suspected, the 64-bit-indexed library is getting listed first in the link command. I thought I had prevented that from happening, but obviously not robustly enough. Not quite sure how best to approach that. I guess the best thing to do would be get Nektar++ built with the 64-bit interface.

**Comment by jwscook** [comment]
Welp, after a `spack clean -m` the intel build builds, `NESO` runs. Only problem is the tests weren't built by `spack install --test root`.

**Comment by jwscook** [comment]
The tests build after:
- Adding `args.append(f"-DENABLE_NESO_TESTS=ON")` to the `cmake_args` method in `NESO-Spack/packages/neso/packages.y`
- Removing `-Wall -Wextra -Wpedantic -Werror ${UNUSED_ARG}` from the NESO `CMakeLists.txt`

However they segfault:

```bash
└─$./test/unitTests 
[==========] Running 20 tests from 6 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from DiagnosticsTest
[ RUN      ] DiagnosticsTest.SizeIncrement
[       OK ] DiagnosticsTest.SizeIncrement (35 ms)
[ RUN      ] DiagnosticsTest.TotalIsSum
[       OK ] DiagnosticsTest.TotalIsSum (24 ms)
[ RUN      ] DiagnosticsTest.ProportionalToMass
[       OK ] DiagnosticsTest.ProportionalToMass (50 ms)
[----------] 3 tests from DiagnosticsTest (109 ms total)

[----------] 4 tests from FFTMKLTest
[ RUN      ] FFTMKLTest.FFT
[       OK ] FFTMKLTest.FFT (0 ms)
[ RUN      ] FFTMKLTest.ForwardSingleModes
[       OK ] FFTMKLTest.ForwardSingleModes (0 ms)
[ RUN      ] FFTMKLTest.BackwardSingleModes
[       OK ] FFTMKLTest.BackwardSingleModes (1 ms)
[ RUN      ] FFTMKLTest.ForwardInverse
[       OK ] FFTMKLTest.ForwardInverse (0 ms)
[----------] 4 tests from FFTMKLTest (1 ms total)

[----------] 8 tests from MeshTest
[ RUN      ] MeshTest.Mesh
[       OK ] MeshTest.Mesh (0 ms)
[ RUN      ] MeshTest.get_left_index
[       OK ] MeshTest.get_left_index (0 ms)
[ RUN      ] MeshTest.evaluate_electric_field
[       OK ] MeshTest.evaluate_electric_field (0 ms)
[ RUN      ] MeshTest.deposit
[       OK ] MeshTest.deposit (0 ms)
[ RUN      ] MeshTest.get_electric_field
[       OK ] MeshTest.get_electric_field (0 ms)
[ RUN      ] MeshTest.solve_for_electric_field_fft
[       OK ] MeshTest.solve_for_electric_field_fft (0 ms)
[ RUN      ] MeshTest.get_E_staggered_from_E
[       OK ] MeshTest.get_E_staggered_from_E (0 ms)
[ RUN      ] MeshTest.set_initial_field
corrupted size vs. prev_size
Aborted (core dumped)
```

Both NESO and the integration tests run/pass.

**Comment by will-saunders-ukaea** [comment]
Looking at the Nektar source (https://gitlab.nektar.info/nektar/nektar/-/blob/master/cmake/FindMKL.cmake#L38) I think (with my rudimentary cmake) that nektar is asking for the 32b indices version. 

Looking at the docs in the cmake file that ships with MKL (`<mkl-root>/2022.1.0/lib/cmake/mkl/MKLConfig.cmake` for me) can we specifiy that we want the 32b indices version with something like `set(MKL_INTERFACE lp64)` in our cmake?

**Comment by cmacmackin** [comment]
> Looking at the Nektar source (https://gitlab.nektar.info/nektar/nektar/-/blob/master/cmake/FindMKL.cmake#L38) I think (with my rudimentary cmake) that nektar is asking for the 32b indices version.
> 
> Looking at the docs in the cmake file that ships with MKL (`<mkl-root>/2022.1.0/lib/cmake/mkl/MKLConfig.cmake` for me) can we specifiy that we want the 32b indices version with something like `set(MKL_INTERFACE lp64)` in our cmake?

I've already tried that. Unfortunately, only the 64-bit interface is compatible with the SYCL version of MKL. The best option would be to make the choice between 32 and 64 bit configurable for Nektar, so we could make sure it gets built with the latter. We could put in a patch to do that in our Spack repository. No idea how open they would be to implementing it upstream.

**Comment by will-saunders-ukaea** [comment]
Would that not involve us going through nektar and swapping) all the indices arrays for 64b ints not 32b (i.e. I'm assuming they are all currently 32b ints)?

**Comment by cmacmackin** [comment]
Ah, guess it would yeah. I was only thinking of literals in my head.
Possibly they have an index-type defined by the preprocessor or
type-aliasing, which would make things easy, but obviously there is no
guarantee of that.

**Comment by will-saunders-ukaea** [comment]
If we statically link to mkl does this solve the issue?

MKL link tool (https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-link-line-advisor.html#gs.jm5xnj) suggests:
```
-fsycl-device-code-split=per_kernel  ${MKLROOT}/lib/intel64/libmkl_sycl.a -Wl,-export-dynamic -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_ilp64.a ${MKLROOT}/lib/intel64/libmkl_sequential.a ${MKLROOT}/lib/intel64/libmkl_core.a -Wl,--end-group -lsycl -lOpenCL -lpthread -lm -ldl
```

**Comment by cmacmackin** [comment]
@jwscook The issue we've been encountering seems to be related to a bug in Spack (spack/spack#29447). Guess we should switch back to having the tests build in all cases for now.

**Comment by cmacmackin** [comment]
>If we statically link to mkl does this solve the issue?
It seems to, which I didn't expect! I'd like to see if James can still compile though, as I don't know how robust a solution this will be. I had it working with dynamic linking on my computer under certain circumstances, after all!

Longer-term I'm still concerned about the fact Nektar++ and NESO are using these different interfaces. I feel like it could be a recipe for future problems. The viability of changing Nektar++ so it can use either 32 or 64 bit interfaces should be evaluated.

**Comment by cmacmackin** [comment]
OK, this branch is ready for review again. If people could find some time to take another look at it soon, that would be great!

**Comment by jwscook** [comment]
I'll come to this on Monday. But if anyone else can confirm that the static MKL linking works as desired then feel free to merge.

**Pull request merged**
