### PR TITLE
Added template argument to interpolator

### PR DESCRIPTION
**Pull request by JamesEdgeley**
# Description

Newest versions (>=5.3) of Nektar++ have FieldUtils::Interpolator as a template class - this PR adds the argument

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] API change (breaks downstream workflows and requires major semver bump)
- [ ] Requires documentation updates

# Testing

Please describe the tests that you ran to verify your changes and provide instructions for reproducibility. Please also list any relevant details for your test configuration.

- [ ] Test Foo in /test/path/to/file_for_test_Foo.cpp
 - Description of test Foo
- [ ] Test Bar in /test/path/to/file_for_test_Bar.cpp
 - Description of test Bar

**Test Configuration**:

* OS:
* SYCL implementation:
* MPI details: 
* Hardware: 

# Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any new dependencies are automatically built for users via `cmake`
- [ ] I have used understandable variable names
- [ ] I have run `clang-format` against my `*.hpp` and `*.cpp` changes
- [ ] I have run `cmake-format` against my changes to `CMakeLists.txt`
- [ ] I have run `black` against changes to `*.py`
- [ ] I have made corresponding changes to the documentation
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by oparry-ukaea** [comment]
Hi @JamesEdgeley,
I'm updating NESO to use a recent nektar version in #232 and have made a similar change to this one. Is this holding you up? If not, it might be easier to wait for me to merge that (hopefully later on this week)

**Comment by JamesEdgeley** [comment]
Not a problem, I've implemented it locally anyway.  Does your change break support for the older nektar versions?

**Comment by oparry-ukaea** [comment]
Don't remember, to be honest...
Since each NESO commit is locked to a particular nektar commit via the nektar submodule anyway, we (I) haven't really made an effort to make the nektar calls backwards compatible...

**Comment by oparry-ukaea** [comment]
Hi @JamesEdgeley - I included your version of this change in #240, so will close this now.

**Pull request closed without merging**
