### PR TITLE
v0.1.0

### PR DESCRIPTION
**Pull request by will-saunders-ukaea**
# Description

PR to stage v0.1.0 release in.

## Type of change
Versioning.

# Testing
Please do some - we have a variety of systems and it would be nice to find issues before making a release.

# Changes
* Updated NP submodule to v0.5.0 release.

### CODE REVIEW

**Comment by will-saunders-ukaea** [comment]
NESO-Spack submodule has been updated - time to test.

**Review by oparry-ukaea — APPROVED** [review]
All looks fine to me.
Built and tested with gcc/hipsycl.

**Comment by will-saunders-ukaea** [comment]
I tried building the spack environment (gcc + hipsycl) and I am seeing:
```
     361    In file included from /home/js0259/git-ukaea/NESO/solvers/SimpleSOL/EquationSystems/SOLSystem.cpp:4:
  >> 362    /home/js0259/git-ukaea/NESO/solvers/SimpleSOL/EquationSystems/SOLSystem.hpp:6:10: fatal error: CompressibleFlowSolver/Misc/VariableConverter.h: No such file or d
            irectory
     363        6 | #include <CompressibleFlowSolver/Misc/VariableConverter.h>
     364          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

But when I do `spack find -lv nektar` the hash the spack env is using is `+comp_flow`.

**Comment by will-saunders-ukaea** [comment]
The log reads:
```
==> Installing nektar-5.3.0-2022-09-03-ibp22bfpa7rovahfbmy7kftoyxko2fsr [43/45]
==> No binary for nektar-5.3.0-2022-09-03-ibp22bfpa7rovahfbmy7kftoyxko2fsr found: installing from source
==> Already patched nektar
==> nektar: Executing phase: 'cmake'
==> nektar: Executing phase: 'build'
==> nektar: Executing phase: 'install'
==> nektar: Successfully installed nektar-5.3.0-2022-09-03-ibp22bfpa7rovahfbmy7kftoyxko2fsr
  Stage: 0.00s.  Cmake: 7.34s.  Build: 7m 56.20s.  Install: 3.40s.  Post-install: 0.22s.  Total: 8m 7.50s
[+] /opt/spack-v0.21/linux-ubuntu22.04-cascadelake/gcc-12.3.0/nektar-5.3.0-2022-09-03-ibp22bfpa7rovahfbmy7kftoyxko2fsr
```
But the output directory suggests spack didn't patch nektar.

**Comment by will-saunders-ukaea** [comment]
Liberal application of `git clean -fdx; git reset --hard HEAD` to NESO and the nektar submodule seems to have solved this patch issue.

**Comment by cmacmackin** [comment]
Yes, this happens sometimes. Run `rm .spack_patched` and then build again. That should fix it.

**Comment by will-saunders-ukaea** [comment]
Tests passed on Archer2. Running into issues locally related to intel packaging rather than NESO.

**Pull request merged**
