### PR TITLE
Update NESO-Particles submodule to the HDF5 fix

### PR DESCRIPTION
**Pull request by will-saunders-ukaea**
Bumps the NP submodule to the commit which contains the enable c cmake fix for hdf5. Looks like we need this to build on archer2 using the provided hdf5 installs (building hdf5 fails for other reasons). 

Also includes the ParticleLoop.

### CODE REVIEW

**Comment by will-saunders-ukaea** [comment]
Seems this creates new issues building NP on archer2....

**Comment by will-saunders-ukaea** [comment]
With the second update this builds for me on archer2.

**Comment by will-saunders-ukaea** [comment]
Waiting on https://github.com/ExCALIBUR-NEPTUNE/NESO-Particles/pull/38

**Comment by will-saunders-ukaea** [comment]
Tests pass for me with acpp (cuda + omp) (modulo the 1D ones expected to fail) and dpcpp.

**Review by jwscook — APPROVED** [review]

**Pull request merged**
