### PR TITLE
Helper script updates

### LINKED ISSUE #243: Document the geo_to_xml.sh script
Document the helper script for generating nektar xml meshes from gmsh .geo files in the [Generating meshes](https://github.com/ExCALIBUR-NEPTUNE/NESO?tab=readme-ov-file#generating-meshes) section of the top-level readme.

### LINKED ISSUE #261: Accommodate recent spack versions in bash scripts and build instructions
Recent spack versions (e.g. 0.22) generate environment builds in $tmp and create links to them at `<env root>/build-{architecture}-{hash}/spack-build-{hash}`
This breaks some functionality in `activate` and `scripts/run_eg.sh` which assume the builds are at `<env root>/spack-build-{hash}`
The build instructions in `README.md` probably also need updating.

### PR DESCRIPTION
**Pull request by oparry-ukaea**
# Description
Various minor updates to the shell scripts in `/scripts` and accompanying documentation, including coping with build locations used by recent versions of spack.

Resolves #243 
Resolves #261 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change)
- [x] Requires documentation updates

# Testing
No new tests

**Test Configuration**:

OS: Ubuntu 22.04
Compiler: GCC 11.4.0 / OneAPI v2024.1.0
SYCL implementation: Hipsycl v0.9.4 / DPC++ v2024.1.0
MPI details: MPICH v4.0.2
Hardware: CPU (Intel Alder Lake)

# Checklist:

~- [ ] I have added tests that prove my fix is effective or that my feature works~
- [x] New and existing unit tests pass locally with my changes
~- [ ] Any new dependencies are automatically built for users via `cmake`~
- [x] I have used understandable variable names
~- [ ] I have run `clang-format` against my `*.hpp` and `*.cpp` changes~
~- [ ] I have run `cmake-format` against my changes to `CMakeLists.txt`~
~- [ ] I have run `black` against changes to `*.py`~
- [x] I have made corresponding changes to the documentation
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by JamesEdgeley** [comment]
What version of spack are you using and where does it put the builds?  For me spack builds somewhere in /tmp (apparently it's faster) but installs in ~/spack/opt/spack.  The activate script then produces symlinks to the tmp builds rather than the install locations.

**Comment by oparry-ukaea** [comment]
I'm on spack 0.22.
Agree that linking to /tmp isn't ideal, but that was the intended behaviour - it's what spack itself does in the root of the spack env (with less useful names). I reboot my machine so rarely that it wouldn't be a problem for me, but I concede that won't be true for everyone.

Depends what we think these links are for.
I only really use them to look at cmake log files, so the install directory wouldn't be much use to me (although admittedly some of the more useful logs are generated one level above the build stage dirs).

I do agree that `run_eg.sh` should use the installed executables though.
So maybe we link the install dirs instead and I just use the spack-generated links to see the build logs. I'd be happier if I could find a config option to make it name those links differently...

**Comment by JamesEdgeley** [comment]
Happy to keep links to build directories as they are in activate.  For run_eg.sh we can get the install location with something like `spack location -i --first neso`.  Not sure how to query the most recently built version in spack though.

**Comment by cmacmackin** [comment]
Yeah, I'm not thrilled about how it now builds stuff in tmp. Unfortunately there does not seem to be anyway to reconfigure this behaviour. (I think it's only faster on clusters with network file systems, too.  Pretty sure it won't make a difference when we're building on our own machines). It means that when you reboot it might have to completely rebuild nektar++, NESO, etc. Something I've discovered which can at least help to minimize this is using [ccache](https://spack.readthedocs.io/en/latest/config_yaml.html#ccache). Perhaps we should configure this in our environment file.

In terms of the `run_eg.sh` script, probably the easiest thing is to use the executables in the `view` directories.

**Comment by oparry-ukaea** [comment]
Forgot about the views... thanks, I'll use those in the script then.

For the build locations, on a per-user basis I assume we can just change the value(s) for `build_stage` in [config.yaml](https://spack.readthedocs.io/en/latest/config_yaml.html)?

**Comment by cmacmackin** [comment]
>For the build locations, on a per-user basis I assume we can just change the value(s) for build_stage in [config.yaml](https://spack.readthedocs.io/en/latest/config_yaml.html)?

I think the problem with that is it will keep *all* of your spack builds there (e.g., cmake, openblas, fftw, hdf5, etc.) and never delete them. We only want to keep the "develop" spack builds.

**Comment by oparry-ukaea** [comment]
> I think the problem with that is it will keep _all_ of your spack builds there (e.g., cmake, openblas, fftw, hdf5, etc.) and never delete them. We only want to keep the "develop" spack builds.

Yeah that's not ideal either, is it... maybe mitigating a bit with ccache is the way to go for now then.

**Comment by oparry-ukaea** [comment]
run_eg now looks for the most recently modified solver exec in `views` by default; this is ready for review again.

**Comment by JamesEdgeley** [comment]
I have a long standing bug with the views related to hdf5 which I'm not sure how to fix, namely:

```
==> Error: The environment view in /home/jedge/NESO/views/gcc-hipsycl could not be created, because the following two specs project to the same prefix:
    hdf5@=1.14.5%gcc@=13.2.0~cxx~fortran+hl~ipo~java~map+mpi+shared~subfiling~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make arch=linux-ubuntu24.04-skylake, and
    hdf5@=1.14.5%gcc@=13.2.0~cxx~fortran+hl~ipo~java~map+mpi+shared~subfiling~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make arch=linux-ubuntu24.04-skylake.
    To resolve this issue:
        a. use `concretization:unify:true` to ensure there is only one package per spec in the environment, or
        b. disable views with `view:false`, or
        c. create custom view projections.
```

**Comment by will-saunders-ukaea** [comment]
> I have a long standing bug with the views related to hdf5 which I'm not sure how to fix, namely:
> 
> ```
> ==> Error: The environment view in /home/jedge/NESO/views/gcc-hipsycl could not be created, because the following two specs project to the same prefix:
>     hdf5@=1.14.5%gcc@=13.2.0~cxx~fortran+hl~ipo~java~map+mpi+shared~subfiling~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make arch=linux-ubuntu24.04-skylake, and
>     hdf5@=1.14.5%gcc@=13.2.0~cxx~fortran+hl~ipo~java~map+mpi+shared~subfiling~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make arch=linux-ubuntu24.04-skylake.
>     To resolve this issue:
>         a. use `concretization:unify:true` to ensure there is only one package per spec in the environment, or
>         b. disable views with `view:false`, or
>         c. create custom view projections.
> ```

I am also seeing this, only after I moved to a new machine and started using spack v0.23 - could this be a spack 0.23 issue?

**Comment by cmacmackin** [comment]
According to the [spack documentation](https://spack.readthedocs.io/en/latest/environments.html#advanced-view-configuration), it should be possible to simplify the views and avoid these sorts of headaches using something like

```
  view:
    gcc-hipsycl:
      root: views/gcc-hipsycl
      select: ["neso%gcc"]
      link_type: symlink
      link: all
    oneapi-dpcpp:
      root: views/oneapi-dpcpp
      select: ["neso%oneapi"]
      link_type: symlink
      link: all
```
This should put a particular build of NESO and all of its run and link-dependencies in the view, and would be more reliable that using `select: ["%gcc"]`. However, when I tried it the only thing put in the view was NESO itself.

**Comment by JamesEdgeley** [comment]
Issue was that those two hdf5 packages (and some others) used different MPI distributions but this didn't get projected to disambiguate them in the view

**Review by JamesEdgeley — APPROVED** [review]

**Review by cmacmackin — APPROVED** [review]
I haven't had a chance to try this on my computer, but as it works for Owen and James I'm happy to approve.

**Pull request merged**
